{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"A typealias for the "},{"type":"codeVoice","code":"Result"},{"text":" type specialized for the TrustlessSDK, where failures are represented by ","type":"text"},{"code":"TrustlessError","type":"codeVoice"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultValue","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ResultValue","kind":"identifier"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Value"},{"kind":"text","text":"> = "},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Value","kind":"typeIdentifier","preciseIdentifier":"s:12TrustlessSDK11ResultValuea0D0xmfp"},{"kind":"text","text":", "},{"identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/TrustlessError","kind":"typeIdentifier","preciseIdentifier":"s:12TrustlessSDK0A5ErrorO","text":"TrustlessError"},{"text":">","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"Value","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The type of the value in the success case."}]}]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"text":"This type simplifies the handling of operations that can either succeed with a value of type ","type":"text"},{"code":"Value","type":"codeVoice"},{"type":"text","text":" or fail with a "},{"type":"codeVoice","code":"TrustlessError"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"It is used extensively across the SDK in functions that perform asynchronous tasks, such as network requests, which can either produce a result or an error."}],"type":"paragraph"}],"kind":"content"}],"sections":[],"seeAlsoSections":[{"identifiers":["doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultCallback","doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/CancelCallback"],"generated":true,"title":"Request and Response"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/trustlesssdk\/resultvalue"]}],"hierarchy":{"paths":[["doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"ResultValue","kind":"identifier"}],"title":"ResultValue","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"ResultValue","kind":"identifier"}],"externalID":"s:12TrustlessSDK11ResultValuea","roleHeading":"Type Alias","role":"symbol","symbolKind":"typealias","modules":[{"name":"TrustlessSDK"}]},"references":{"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/CancelCallback":{"abstract":[{"text":"A typealias for a closure used to cancel an ongoing operation.","type":"text"}],"identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/CancelCallback","title":"CancelCallback","url":"\/documentation\/trustlesssdk\/cancelcallback","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CancelCallback"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CancelCallback"}]},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/TrustlessError":{"role":"symbol","navigatorTitle":[{"text":"TrustlessError","kind":"identifier"}],"title":"TrustlessError","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/TrustlessError","kind":"symbol","abstract":[{"type":"text","text":"Describes errors that can occur within the TrustlessSDK."}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TrustlessError","kind":"identifier"}],"url":"\/documentation\/trustlesssdk\/trustlesserror"},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK":{"abstract":[],"kind":"symbol","role":"collection","url":"\/documentation\/trustlesssdk","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK","type":"topic","title":"TrustlessSDK"},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/ResultCallback":{"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultCallback"}],"title":"ResultCallback","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultCallback","type":"topic","url":"\/documentation\/trustlesssdk\/resultcallback","abstract":[{"text":"A typealias for a callback function that is invoked with a ","type":"text"},{"code":"ResultValue","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"text":"ResultCallback","kind":"identifier"}]},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/ResultValue":{"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ResultValue","kind":"identifier"}],"title":"ResultValue","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultValue","type":"topic","url":"\/documentation\/trustlesssdk\/resultvalue","abstract":[{"type":"text","text":"A typealias for the "},{"type":"codeVoice","code":"Result"},{"type":"text","text":" type specialized for the TrustlessSDK, where failures are represented by "},{"code":"TrustlessError","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"text":"ResultValue","kind":"identifier"}]}}}