{"metadata":{"roleHeading":"Type Alias","modules":[{"name":"TrustlessSDK"}],"role":"symbol","navigatorTitle":[{"text":"ResultValue","kind":"identifier"}],"externalID":"s:12TrustlessSDK11ResultValuea","title":"ResultValue","symbolKind":"typealias","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"ResultValue","kind":"identifier"}]},"seeAlsoSections":[{"identifiers":["doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultCallback","doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/CancelCallback"],"generated":true,"title":"Request and Response"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResultValue","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Value","kind":"genericParameter"},{"text":"> = ","kind":"text"},{"preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier","text":"Result"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:12TrustlessSDK11ResultValuea0D0xmfp","text":"Value","kind":"typeIdentifier"},{"kind":"text","text":", "},{"identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/TrustlessError","text":"TrustlessError","preciseIdentifier":"s:12TrustlessSDK0A5ErrorO","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The type of the value in the success case.","type":"text"}],"type":"paragraph"}],"name":"Value"}]},{"content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"text":"This type simplifies the handling of operations that can either succeed with a value of type ","type":"text"},{"type":"codeVoice","code":"Value"},{"type":"text","text":" or fail with a "},{"type":"codeVoice","code":"TrustlessError"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"It is used extensively across the SDK in functions that perform asynchronous tasks, such as network requests, which can either produce a result or an error."}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"type":"text","text":"A typealias for the "},{"type":"codeVoice","code":"Result"},{"text":" type specialized for the TrustlessSDK, where failures are represented by ","type":"text"},{"type":"codeVoice","code":"TrustlessError"},{"text":".","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultValue"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/trustlesssdk\/resultvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK":{"type":"topic","kind":"symbol","title":"TrustlessSDK","url":"\/documentation\/trustlesssdk","role":"collection","abstract":[],"identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK"},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/TrustlessError":{"url":"\/documentation\/trustlesssdk\/trustlesserror","kind":"symbol","abstract":[{"type":"text","text":"Describes errors that can occur within the TrustlessSDK."}],"navigatorTitle":[{"text":"TrustlessError","kind":"identifier"}],"title":"TrustlessError","role":"symbol","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/TrustlessError","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TrustlessError"}]},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/ResultValue":{"role":"symbol","title":"ResultValue","abstract":[{"text":"A typealias for the ","type":"text"},{"type":"codeVoice","code":"Result"},{"type":"text","text":" type specialized for the TrustlessSDK, where failures are represented by "},{"code":"TrustlessError","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/trustlesssdk\/resultvalue","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ResultValue"}],"identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultValue","navigatorTitle":[{"text":"ResultValue","kind":"identifier"}],"type":"topic"},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/ResultCallback":{"type":"topic","url":"\/documentation\/trustlesssdk\/resultcallback","abstract":[{"type":"text","text":"A typealias for a callback function that is invoked with a "},{"code":"ResultValue","type":"codeVoice"},{"type":"text","text":"."}],"title":"ResultCallback","role":"symbol","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultCallback","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResultCallback","kind":"identifier"}],"navigatorTitle":[{"text":"ResultCallback","kind":"identifier"}]},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/CancelCallback":{"role":"symbol","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/CancelCallback","abstract":[{"text":"A typealias for a closure used to cancel an ongoing operation.","type":"text"}],"title":"CancelCallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CancelCallback","kind":"identifier"}],"url":"\/documentation\/trustlesssdk\/cancelcallback","kind":"symbol","navigatorTitle":[{"text":"CancelCallback","kind":"identifier"}],"type":"topic"}}}